version: '3.8'

services:
  rabbit:
    image: rabbitmq:3.9.11-alpine
    ports:
      - 5672:5672
    networks:
      - internal

  checker:
    image: notion-autocomplete:latest
    deploy:
      replicas: 2
    command: celery -A celeryapp worker -l INFO -Q checker -n checker@%h
    depends_on:
      - rabbit
    networks:
      - internal
    volumes:
      - .:/app
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_API_VERSION=${NOTION_API_VERSION}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_API_TOKEN=${IGDB_API_TOKEN}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}

  updater:
    image: notion-autocomplete:latest
    deploy:
      replicas: 1
    command: celery -A celeryapp worker -l INFO -Q updater -n updater@%h
    depends_on:
      - rabbit
    networks:
      - internal
    volumes:
      - .:/app
    environment:
      - NOTION_API_TOKEN=${NOTION_API_TOKEN}
      - NOTION_API_VERSION=${NOTION_API_VERSION}
      - IGDB_CLIENT_ID=${IGDB_CLIENT_ID}
      - IGDB_API_TOKEN=${IGDB_API_TOKEN}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}

  beat:
    image: notion-autocomplete:latest
    deploy:
      replicas: 1
    command: celery -A celeryapp beat -l INFO
    depends_on:
      - rabbit
    networks:
      - internal
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_BACKEND_URL=${CELERY_BACKEND_URL}

  flower:
    image: mher/flower
    ports:
      - 5555:5555
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - FLOWER_PORT=5555
    depends_on:
      - rabbit
    networks:
      - internal
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.flower.entrypoints=web"
      - "traefik.http.routers.flower.rule=PathPrefix(`/flower/`)"
      - "traefik.http.services.flower.loadbalancer.server.port=5555"

networks:
  internal:
    external: false
